### ISSUE TITLE
New Feature: Add support for faceted search within Native Search override (ie. layered nav widget)

### ISSUE THREAD

**Issue by virtuman** [algolia/algoliasearch-wordpress#156]
### What did you expect to happen?
When Native Search is enabled, it should optionally allow to specify what fields for facets should be returned within this original call to algolia. 

Within `Algolia_Search->pre_get_posts` add `apply_filters` on received `$results`. 
It may be needed for many reasons, but this would also open a possibility for additional integrations and widgets, ie - widget to auto-generate faceted sidebar, etc...

Enabling Faceting on Native Search would require additional options, ie: 

1. Use Faceting on Taxonomy Pages [select list with taxonomy(ies) to enable faceting];
2. Use Faceting on Search Result Pages (ie. archive/search)

If faceting is enabled for one of the options above, then name all parameters and div holder elements in a way to be able to auto-instantiate instantsearch, which in turn will take over consequent searches from the same page and will continuously re-render faceted nav sidebar within the same elements that were built using PHP on page open.

### What happened instead?
Currently no support for facets in algolia wordpress plugin

### Technical info
* WordPress version: 4.5.3
* Algolia Search plugin version: 0.2.8

**Comment by rayrutjes** [comment]
This is a very interesting one @virtuman.
We where kind of opportunistic when we decided to implement the native search overriding.
Indeed, once we had a working indexing logic, it was very easy to override the search on the backend side of things.

That being said, Algolia works best when implemented in the frontend and that is really what we want to push in the end. Not even sure we want to keep backend search overriding which becomes kind of useless once we have an easy to integrate frontend search.

What we miss for now is that easy way of integrating / configuring the instantsearch.js experience. This is really our focus right now as a lot of users are trying to implement that kind of search experience where you get instantaneous results and are able to filter on criterias like tags , taxonomies or authors.

Any suggestion on this would be much appreciated.

We are currently exploring shortcodes to see if it could be a good fit, but we still need to find a way to let users add and customise instantsearch.js widgets which will result in custom code.

**Comment by rayrutjes** [comment]
Hey @virtuman ,
Since version 0.4.0 we support instantsearch.js out of the box.
It includes a simple template that holds HTML + JS that can easily be tweaked.

As explained, Algolia really makes more sense in the frontend because it then avoid an additional roundtrip to the server which makes results appear in milliseconds.

For now we do not want to the use of Algolia in the backend.

You can find more information on the documentation: https://community.algolia.com/wordpress/instantsearch.html

I'm closing this for now as it relates to an older version of the plugin. Feel free to open a new issue if you still think we can improve the plugin. Your feedback has been valuable so far, I'm looking forward to hear more from you ❤️
