### ISSUE TITLE
Add handler for 'delete_item' tasks

### ISSUE THREAD

**Issue by Mamaduka** [algolia/algoliasearch-wordpress#229]
Currently in core plugin watchers deletion action are handled via `sync_item` tasks. It would be nice to have separated handler for item deletion and handle those via `$client->deleteObject('objectID')` method.

There are few cases where using `sync_item` might fail:

- Not all functions/methods file action before deleting items from DB.
- Task are handled async, which means  there will be cases when task is fired, item is already deleted from DB. In that case `Algolia_Index::extract_item()` will return `null` and `Algolia_Index::handle_task()` will throw exception.

**Comment by rayrutjes** [comment]
Owe, you are right @Mamaduka , I just checked and there is something wrong in our logic.
Let me do a quick fix, and go more into the details after.

Thx for the issue, very much appreciated!

**Comment by Mamaduka** [comment]
@rayrutjes happy to provide PR for this fix. I think that would be good starting point to make logic better in `Algolia_Index::handle_task()`. Ideally it should support custom task handlers, if extensions want to handle things differently.

I understand why that method is final, so to make it more extendable I suggest adding somethings like this after `switch` statement.

```
do_action( 'algolia_index_handle_task', $this->index, $this->task );
```

**Comment by rayrutjes** [comment]
@Mamaduka a PR is underway. Please bear with me and lets discuss from there. You are making some points, but others might conflict with some of the principles we wanted the task queue to follow.

**Comment by Mamaduka** [comment]
Totally makes sense. Looking forward to PR and we can continue discussion from there.

**Comment by rayrutjes** [comment]
@Mamaduka please take a look at #234 and let me know what you think.

Regarding the queue, we do not want to introduce some kind of 'delete_item' because only the state at the time of processing the task matters.

In the case of this issue, we didn't handle the case where a post would go from 'published' to 'deleted' without passing being 'trashed' which can happen. The PR fixes that.

Regarding the "custom task handler", we do not claim our task queue system is re-usable in any way. This would require is to decouple the code even more, and would probably feel a little bit over-engineered. That being said, the idea of creating a separate package for handling queues in WordPress has crossed my mind, but I have had not time to tackle this ;)

Feel free to react on the PR!

**Comment by Mamaduka** [comment]
@rayrutjes thanks for PR. I think that's good fix (left comment in code for minor issue).

I agree with you about "custom task handler", I think currently main method can handle all use cases.
