### ISSUE TITLE
Request: Disable autocomplete on individual search forms

### ISSUE THREAD

**Issue by ethansmith** [algolia/algoliasearch-wordpress#267]
This is more of a request than a bug. A theme I'm working with comes with a variety of search forms that each are scoped with a specific set of filters. For example, one searches within members of a particular group; another searches for things the current user has authored within a particular post type. In none of these cases does the content presented in my global autocomplete menu match the scope of the search form.

I'd ultimately love to create a number of unique autocomplete instances for each of these use cases, augmenting the existing functionality.

However, in the short term I'd like to have a way to selectively prevent the autocomplete script from being attached to some of these forms. Perhaps via a class name like `disable-autocomplete` or something similar?

Thanks!

**Comment by rayrutjes** [comment]
Hi @ethansmith thank you for submitting this ;)

Since the latest releases you can easily customize the autocomplete experience by copy pasting the `templates` folder of the plugin into your theme folder by renaming it to `algolia`.

Then, you can easily change the autocomplete default selector at this line and add your custom class: https://github.com/algolia/algoliasearch-wordpress/blob/master/templates/autocomplete.php

I hope that helps, let me know if something is unclear!

**Comment by ethansmith** [comment]
Perfect. Exactly what I was looking for!

**Comment by rayrutjes** [comment]
Kool! Don't hesitate to open other issues!
