### ISSUE TITLE
Add ability to save settings during a full re-index

### ISSUE THREAD

**Issue by Cyapow** [algolia/algoliasearch-wordpress#420]
### What did you expect to happen?
I expected to keep settings (was easy enough to fix but just unexpected)

### What happened instead?
Full re-indexed moving from staging server to live server and lost all ranking settings as well as synonyms

### Technical info
* WordPress version: 4.6.1
* Algolia Search plugin version: 1.4.1

**Comment by rayrutjes** [comment]
Thanks for submitting this @Cyapow ,

An easy solution would be the following:
- [ ] Introduce a constant `ALGOLIA_KEEP_SETTINGS`
- [ ] When re-indexing, get the current settings if index exists and keep them

This solution has some drawbacks:
- If a plugin hooks into the settings, it will never get to Algolia unless you de-index and then re-index
- If the index settings gets into a weird state, we also need to de-index then re-index to get back to a correct state

Maybe allowing to reset the settings on a per index basis would make sense.

WDYT?

**Comment by Cyapow** [comment]
I think thats an acceptable solution to be honest. If you have a third party plugin manipulating the plugin hooks thats your responsibility to know the settings might get into a weird state

**Comment by rayrutjes** [comment]
I started working on the introduction of a new constant to handle this and realized that it could get a bit complex in case you use `replicas`.

Indeed, the question would then be do we also keep the settings of replicas?

@Cyapow I agree that we should not override synonyms by default, because the Algolia dashboard is more convenient to manage those.
Regarding the other ranking settings, is there a reason you don't want to use the filters we provide? https://community.algolia.com/wordpress/indexing-settings.html#custom-index-settings-example

If your code is under version control, it makes a lot of sense to add the configuration for the settings to your code. That way you ensure on every re-index you keep the chosen configuration but you can also benefit from upcoming enhancement we might provide.

WDYT?

**Comment by rayrutjes** [comment]
I made sure we keep synonyms if none provided from the WordPress side in #453 .

This is a first step that I will push as part of 1.6.0 because it really makes sense.

I'm looking forward for your feedback regarding the custom settings related to ranking. I'm afraid any kind of "merging" strategy will be hard to debug and understand for users, and we definitely need WordPress to be the owner of this.

**Comment by Cyapow** [comment]
@rayrutjes this may work mate. I hadn't seen the WP filters. I will take a look.

Thanks
