### ISSUE TITLE
No IPv6 support yet

### ISSUE THREAD

**Issue by webernetz** [algolia/algoliasearch-wordpress#441]
Hello guys

just one notice: www.algolia.com has no IPv6 support yet. I am running my blog (almost) completely dual-stacked, i.e., IPv6 and legacy IP. However, since I enabled your plugin an IPv6-only connection will not work completely. Please consider using IPv6 for your servers.

<pre><code>weberjoh@jw-nb15-lx:~$ dig www.algolia.com aaaa

; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.algolia.com aaaa
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2000
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.algolia.com.               IN      AAAA

;; AUTHORITY SECTION:
algolia.com.            3600    IN      SOA     aiden.ns.cloudflare.com. dns.cloudflare.com. 2023150074 10000 2400 604800 3600

;; Query time: 34 msec
;; SERVER: 192.168.120.22#53(192.168.120.22)
;; WHEN: Wed Nov 30 21:06:04 CET 2016
;; MSG SIZE  rcvd: 104
</code></pre>

**Comment by asurak** [comment]
The IPv6 support is planned for `algolia.com` (website), `algolia.net` (API) and `algolianet.com` (API). Unfortunately we don't have a precise timeline yet as this change is very sensitive due to the sadly broken IPv6 stack of many networks and systems. We plan to open a new cluster that will have IPv6 from the day one in order to avoid issues and once we see that it's resolved, we'll roll the changes to the rest of the infrastructure.

**Comment by rayrutjes** [comment]
@webernetz I'm closing this issue as it does not directly relate to this plugin ;)
