### ISSUE TITLE
Combining Posts and Pages into one index for results

### ISSUE THREAD

**Issue by rtwlabs** [algolia/algoliasearch-wordpress#513]
### What did you expect to happen?

Testing the plugin for a clients travel site where we have lots of blog posts and static pages full of content. The pages being more evergreen guide style content while blog posts the everyday stuff. 

When indexing all searchable posts we want to pull back one combined listing of posts and pages for readers to select from. With weighting to favour the pages on the site as they contain more relevant content over a blog post.

### What happened instead?

When indexing all searchable posts we seem to only pull back data on blog posts and to a degree weighted by post date and pages are omitted. Where as when we also add in pages as an option we get a second listing of results on the instant search giving us two separate distinct listings. 

### How can we reproduce this behavior?

This can be reproduced by opting to index both searchable posts and pages.

Can you provide a link to a page which shows this issue?

Search currently being tested on a closed staging site but access can be granted if need be.

### Technical info
* WordPress version: Wp 4.7.2
* Algolia Search plugin version: 1.7.0

Not sure if I've just missed the docs on how to make this happen or if I'm asking the wrong question. In a perfect setup we have one results list combining blog posts and pages together with the ability to weight pages over posts due to the nature of the site and content

**Comment by rayrutjes** [comment]
Hi @rtwlabs ,

Sorry about the delay,

In your case you will indeed alter the customRanking a bit to reflect your intentions.

Basically what you will want to do [is push a custom attributes](https://community.algolia.com/wordpress/advanced-custom-fields.html#push-custom-fields-to-algolia) as part of all your records of the searchable posts index called `is_page` (the naming of this attribute is up to you).

This attribute should equal 1 if the post type === 'page' or 0 otherwise.
*Warning*: ensure this attribute is an integer and that it is not surrounded with quotes in the Algolia dashboard, otherwise ranking won't work as expected.

Once you managed to push that attribute as part of your records, you will need to [add the new rule on top of your customRanking formula](https://community.algolia.com/wordpress/advanced-custom-fields.html#integrate-custom-fields-in-your-custom-ranking).
The added rule should be `desc(is_page)`.

After a full re-index, pages will now always appear first.

Let me know if that works out, and feel free to re-open to ask more info.
