### ISSUE TITLE
Product Attribute Filter Logic

### ISSUE THREAD

**Issue by SolidDev** [algolia/algoliasearch-wordpress#515]
I found this page in the documentation that does help me display any and all attributes I'd like as search filters (https://community.algolia.com/woocommerce/frequently-asked-questions.html#can-i-choose-the-attributes-that-are-available-in-the-filters-). 

As it works right now, all attribute filters listed in `$attribute_ids_to_keep ` are displayed as filters. Once the results are narrowed down far enough to the point where an attribute is no longer relevant, those attribute filters are hidden, which is great! 

I'd like to hide all attribute filters until specifically the point when a product-sub-category filter chosen. This way, visitors are not bombarded with all possible product attributes when the search query is still broad and would display too many attribute filters.

Is there enough customization available for the logic that displays the search filters to achieve the behavior I'm looking for?

**Comment by rayrutjes** [comment]
Unfortunately, and as of today, there is no way to do this.

You could probably get away doing so with a custom [instantsearch.js implementation](https://community.algolia.com/instantsearch.js/documentation/) instead of using the one provided in the `template` dir.

For further WC support, please ask your questions on the [forum](https://discourse.algolia.com/c/wordpress) given this repository relates only to the Algolia plugin for WordPress.

Thanks for your support!
