### ISSUE TITLE
Question: doesn't splitting posts and pages automatically double cost?

### ISSUE THREAD

**Issue by chris-schmitz** [algolia/algoliasearch-wordpress#559]
This isn't an issue, more just me trying to understand. 

If the post and pages (and any other custom post type) are split into their own separate indices, searching multiple indices creates an operation per index, and pricing charges by operation doesn't this mean we're automatically multiplying the cost of Algolia by the number of post types we want to include?

I'm trying to decide if I want to use this plugin vs rolling my own server side code to push to Algolia. I would much rather use this plugin, but if the ongoing cost increase of using this plugin far outweighs the time to code it myself once I'd have to go with a custom build. 

All that said, I think I'm just misunderstanding either the way this plugin works or the way Algolia charges (or maybe both). 

Could someone help me understand please?

**Comment by rayrutjes** [comment]
Hi @chris-schmitz sorry about the delay here.

Today Algolia offers different plans which are limited by the number of records and operations.

Most often the number of records is the limiting factor and you don't have to worry about the number of operations. But this of course depends on your website and the search experience you are providing.

We use multiple indices for autocomplete dropdown experiences because it provides a better end user experience. Every content type can potentially have its own custom ranking etc.
That being said you are free to store all of those in the same index.

You can also use the PHP Api Client if you feel like doing a custom implementation that is more aligned with your use case.

I'm closing this here, but feel free to discuss the topic on [our forum](https://discourse.algolia.com/) ;)
