### ISSUE TITLE
Merge autocompleteTypes and additionalAttributes

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-wordpress#56]
Is it possible to merge those attributes? At least in the `algoliaSettings` JavaScript variable.

**Comment by maxiloc** [comment]
Yes we can :+1:

**Comment by rayrutjes** [comment]
Not sure if this issue is still valid in the latest version of the plugin, 0.2.5 at the time of writing this.
Please note however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
