### ISSUE TITLE
How to search Clickable Images with Algolia in Wordpress?

### ISSUE THREAD

**Issue by pmahmoudzadeh** [algolia/algoliasearch-wordpress#582]
### What did you expect to happen?

I am using Wordpress for my website and my website is completely images based like https://pixabay.com/. When search a word (e.g. Cat), it shows "Cat" but when I click on "Cat" it will redirect me to blank page without any images like here https://snag.gy/YhK4W0.jpg. 

I am not looking for instant search results with images. I need a drop-down menu which displays relevant results even before my users finish typing their queries (like here https://snag.gy/UCgnHh.jpg), then click on queries to redirect them to appropriate images. 

Also, is there any way to re-index my indexes automatically? or Any setting to set a time for this?

I don't want to display my title indexes in search results (like here https://snag.gy/U41YzN.jpg), how to remove them?

### Technical info
* WordPress version: 4.7.4
* Algolia Search plugin version: 2.2.1 

Thanks!

**Comment by rayrutjes** [comment]
Hi @pmahmoudzadeh , sorry about the delay,

**Blank tag pages:**
I'm not sure what the issue could be, do you have a live example so that I can take a look?
Looks like either the URL is wrong, or you expect it to be generated differently than the standard tag-way.

**Custom look & feel:**
To customize the look and feel, you need to add custom CSS rules to your theme.
You can also override what is displayed by following the guide here: https://community.algolia.com/wordpress/customize-autocomplete.html

**Automatic re-indexing:**
First indexing needs to be done manually. After that your content should stay in sync with Algolia so that you do not need to take any further actions.

**Hide labels in autocomplete dropdown:**
Here is a CSS rule to hide the headers: https://discourse.algolia.com/t/hide-description-and-or-images-in-autocomplete-dropdown-in-algolia-plugin-for-wordpress/1360/3?u=rayrutjes

I hope that helps.
