### ISSUE TITLE
Add filter to allow for forcing settings update on re-index

### ISSUE THREAD

**Issue by hereswhatidid** [algolia/algoliasearch-wordpress#594]
I would like to be able to force an update of an index's settings during the re-index even if that index already exists. Currently, as of 2.0.0, the plugin no longer updates an index's settings if the index is already defined and there is no way other than using the Algolia interface to update those settings.

I've set it up on my local install and can submit a pull request but wanted to run it through here first:

https://github.com/hereswhatidid/algoliasearch-wordpress/commit/91f0666a13fe8c82b2d524d936e41aded39f0d03

**Comment by rayrutjes** [comment]
That does look very good, Thanks a lot.

Please do submit the PR.

Some comments:
- I would remove this line: https://github.com/hereswhatidid/algoliasearch-wordpress/blob/91f0666a13fe8c82b2d524d936e41aded39f0d03/includes/indices/class-algolia-index.php#L244
I think it brings little value given we can already check if the second argument is a given index.
- https://github.com/hereswhatidid/algoliasearch-wordpress/blob/91f0666a13fe8c82b2d524d936e41aded39f0d03/includes/indices/class-algolia-index.php#L245
I would go for `$force_settings_update === false` to make it a bit easier to read.
- If you can add the filter to the docs here it would be perfect: https://github.com/hereswhatidid/algoliasearch-wordpress/blob/91f0666a13fe8c82b2d524d936e41aded39f0d03/docs/src/filters.md
Otherwise I'll take care of it.

Again, thank you. I'll make sure to handle this quickly.

**Comment by rayrutjes** [comment]
Merged in #607 
Will release soon!

Please bear with me.
