### ISSUE TITLE
Cannot specify attributesToIndex and searchableAttributes at the same time

### ISSUE THREAD

**Issue by jeremymoore** [algolia/algoliasearch-wordpress#621]
### What happened?
While attempting to push settings using the newest version of the algolia plugin i'm seeing that attributesToIndex has been deprecated, but I can't use searchableAttributes at the same time. I see that the plugin code still uses attributesToIndex all over. Is this changed in an upcoming release? Or, am i missing something? 

### How can we reproduce this behavior?
```	
add_filter( 'algolia_searchable_posts_index_settings', array($this, 'setup_searchable_posts_index_settings'));

function setup_searchable_posts_index_settings( array $settings ) {

		$default = array(
	    'attributesForFaceting' => array(
				'post_type',
				'post_title',
				'taxonomies_hierarchical',
				'taxonomies',
			),
			'customRanking' => array(
				'asc(post_title)'
			),
			'searchableAttributes' => array(
				'person_desk_phone',
				'person_work_cell',
				'person_work_email'
			)
		);

		return array_merge($settings, $default);
	}

```

### Can you provide a link to a page which shows this issue?
<img width="384" alt="screen shot 2017-06-15 at 1 40 23 pm" src="https://user-images.githubusercontent.com/1245814/27196564-8ffacd10-51d0-11e7-9d44-18558e4a58c4.png">

### Technical info
* WordPress version: 4.8
* Algolia Search plugin version: 2.3.0

**Comment by rayrutjes** [comment]
Hi @jeremymoore ,

Indeed, the API now recommends using the new "searchableAttributes" syntax because it is a more explicit name.

That being said, attributesToIndex will always be supported.

We will keep attributesToIndex for now because otherwise we might break existing implementations.

In your custom code, you should use attributesToIndex as well.

I hope that helps, let me know what you think.
