### ISSUE TITLE
Powered by link goes to /undefined

### ISSUE THREAD

**Issue by Jerskouille** [algolia/algoliasearch-wordpress#65]

**Comment by FileSubmit** [comment]
this is still unresolved.
in template.js on 62nd line the problematic code:

`<div class="footer">powered by <img width="45" src="' + algoliaConfig.plugin_url + '/front/algolia-logo.png"></div>'`

**Comment by rayrutjes** [comment]
This issue should be fixed in the new version, 0.2.5 at the time of writing this.
Please not however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
