### ISSUE TITLE
Index product variations

### ISSUE THREAD

**Issue by greatwitenorth** [algolia/algoliasearch-wordpress#67]
It'd be nice if product variations could also be indexed. For example if I have a variable product 'Apple' and I have a variation 'Red' when I type red in the search box 'red', apple does not currently show up. I didn't see an option to index the post type product_variation either. So I'm not sure if that's a wordpress issue, or you're just not making that post type available for indexing.

**Comment by maxiloc** [comment]
@greatwitenorth sorry for the late reply, I am letting this open, I will see what we can do about this

**Comment by rayrutjes** [comment]
Hi @greatwitenorth , we have released a new version of the plugin, 0.2.5 at the time of writing this.
Please not however that this new version is not compatible with 0.0.1 and that the features have changed.

In your case, the new plugin won't solve your issue because we removed WooCommerce support from the scope of the plugin. You can read more about our choice in  [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html).

That said, we will release a WooCommerce search extension that will be extending this plugin as soon as possible.

In the meantime, if you have feature requests regarding that WooCommerce extension, please open issues here: https://github.com/algolia/algoliasearch-woocommerce/issues
