### ISSUE TITLE
images in the post content is not pushed to algolia

### ISSUE THREAD

**Issue by suriyabaskaran** [algolia/algoliasearch-wordpress#69]
Images linked to my wp post content (inline) is not push along with text attribute at algolia using this plugin. Is there a way for it work?

**Comment by maxiloc** [comment]
@suriyabaskaran Sorry for the late reply. I am not sure I get your question. Can you give me a bit more details ?

**Comment by suriyabaskaran** [comment]
@maxiloc , My posts are having images linked. But i couldnt see those images details at algolia indices(field key is `text`). I have attached my algolia indices for a record and the blog page from my site.

https://www.runway2street.com/magazine/5-statement-coats-to-wear-this-winter

Algolia Indices:
[Algolia_5 Statement Coats To Wear This Winter.pdf](https://github.com/algolia/algoliasearch-wordpress/files/68133/Algolia_5.Statement.Coats.To.Wear.This.Winter.pdf)

**Comment by rayrutjes** [comment]
Hi @suriyabaskaran, not sure if this issue is still valid in the latest version of the plugin, 0.2.5 at the time of writing this.
Please not however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
