### ISSUE TITLE
Plugin disables default search page

### ISSUE THREAD

**Issue by listedegarde** [algolia/algoliasearch-wordpress#70]
**Problem:**

After activating the plugin, the default WordPress search page returns "Nothing Found".  

**Expected Result:**

Default search page should work as before the plugin is activated.

**Tested using:**

WordPress 4.3.x
Algolia plugin 0.1

**To reproduce:**

1. Install and setup Algolia Search Wordpress Plugin (this plugin)
2. Visit the search page (?s=searchterm)
3. No search results are returned, event when searching a term that exists on the website.

**Comment by rayrutjes** [comment]
Hi @listedegarde, this issue should be fixed in the new version, 0.2.5 at the time of writing this.
Please not however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
