### ISSUE TITLE
instantsearch.widgets.menuSelect is not a function

### ISSUE THREAD

**Issue by codedbyrob** [algolia/algoliasearch-wordpress#741]
When trying to add a menuSelect widget, I get the console error `Uncaught TypeError: instantsearch.widgets.menuSelect is not a function`. Am I right in thinking that this plugin ships with InstantSearch v1, whereas menuSelect is a v2 feature?

If so, is there any way of utilising menuSelect with this plugin?

Thanks a lot

### Technical info
* WordPress version: 4.7.2
* Algolia Search plugin version: 2.10.2

**Comment by rayrutjes** [comment]
Hi @codedbyrob ,

You are right to assume the plugin ships only with v1 thus far because we need to maintain backward compatibility.

I'm not sure there is a `menuSelect` widget in v1 though.

One of your options would be to disable instantsearch in the frontend, and load the v2 library from a CDN and do your custom templating.

**Comment by codedbyrob** [comment]
Hey @rayrutjes,

Thanks very much for confirming, and for the suggested solution. Think I've got my approach sorted now.

**Comment by alishanster** [comment]
Hello @rayrutjes 
Did we still not get menuSelect widget in Algolia Search plugin version: 2.11.2? 
If not, could you hint me more details on how to load the v2 library from a CDN and do custom templating. Right now I have 'Use Algolia with Instantsearch.js' option selected and I am doing editings in instantsearch.php file. 

P.S. My goal is also to make a drop-down menu selector like here: https://community.algolia.com/instantsearch.js/v2/widgets/menuSelect.html#example

Thank you.
