### ISSUE TITLE
How to set the number of autocomplete suggestions?

### ISSUE THREAD

**Issue by SamAnthonyWP** [algolia/algoliasearch-wordpress#75]
Hey guys,

I think there is a spot for this in the algolia search menu inside wordpress, but setting the number of "auto-completion suggestions" doesn't change anything on the front end.

Any help would be greatly appreciated!

-Sam

**Comment by maxiloc** [comment]
@SamAnthonyWP Are you using the develop branch ?

**Comment by SamAnthonyWP** [comment]
No

On Tuesday, January 26, 2016, maxiloc <notifications@github.com> wrote:

> @SamAnthonyWP <https://github.com/SamAnthonyWP> Are you using the develop
> branch ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/algolia/algoliasearch-wordpress/issues/75#issuecomment-174881512>
> .
>


-- 

*Sam Anthony*

*Director of Development*



*TheSiteEdge*

*Minneapolis, MN*

*Cell:  414-477-7100 <4144777100>*

*thesiteedge.com <http://thesiteedge.com/>*

*01**webDesign |* *02**SEO | **03**contentWriting |* *04**webAnalytics | *
*05**onlineMarketing*

**Comment by maxiloc** [comment]
Ok I would recommand to use the develop branch which contains the most recent version of the extension

**Comment by rayrutjes** [comment]
Hi @SamAnthonyWP , this issue should be fixed in the new version, 0.2.5 at the time of writing this.
Please not however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
