### ISSUE TITLE
Partial search from the words/string

### ISSUE THREAD

**Issue by dhvani-barot** [algolia/algoliasearch-wordpress#754]
### Try to search for " What if I'm dilating" in our site[ https://staging.birthpedia.net/ ] search box.

https://staging.birthpedia.net/

### Technical info
* WordPress version: Version 4.9.5
* Algolia Search plugin version: Version 2.10.2

Note that we're new to this plugin and don't know which rule we need to create to perform this kind of search. Where to add the rule etc.

Your help appreciated !!

**Comment by rayrutjes** [comment]
Hello @dhvani-barot ,

Your issue is not specifically tied to this repository and is more a general relevance question.

Let me still try to give you some clues here.

I suggest you try to change the [optional words parameter](https://www.algolia.com/doc/guides/textual-relevance/optional-words/) and/or the [queryType](https://www.algolia.com/doc/api-reference/api-parameters/queryType/) to `prefixAll`.
You could also look into [removeWordsIfNoResult](https://www.algolia.com/doc/api-reference/api-parameters/removeWordsIfNoResults/).

All those parameters can be configured directly through the ranking or display tab of the Algolia dashboard when on your index. I hope that helps.
If you need further assistance, please reach out to support@algolia.com and make sure you share with us read access to your account.

**Comment by dhvani-barot** [comment]
Thank you.
I have e-mailed you.

**Comment by rayrutjes** [comment]
👍 closing this issue in the meantime.
