### ISSUE TITLE
XSS in templates/default/templates.php

### ISSUE THREAD

**Issue by stevenatwork** [algolia/algoliasearch-wordpress#78]
Example:

https://wp.sr-sandbox.com/?instant=1&s="%0D%0A</script><script>alert(1)</script>#q=%0D%0A<script>%0D%0Aalert(1)</script>&page=0&refinements=[]&numerics_refinements={}&index_name="all"

```
/algoliasearch-wordpress-master/templates/woo/templates.php:59
/algoliasearch-wordpress-master/templates/default/templates.php:59
```

```php
<?php $s = isset($_GET['s']) ? $_GET['s'] : "" ?>
<input value="<?php echo $s; ?>"......
```

$s should be escaped using htmlentities($s, ENT_QUOTES, 'UTF-8');

**Comment by maxiloc** [comment]
@stevenatwork Can you try on the develop branch and tell me if you manage to reproduce ?

**Comment by stevenatwork** [comment]
Still exists on that branch
![image](https://cloud.githubusercontent.com/assets/17074219/13062161/8d4a81be-d490-11e5-8d3b-87105f0a59cf.png)

**Comment by rayrutjes** [comment]
Hi @stevenatwork , not sure if this issue is still valid in the latest version of the plugin, 0.2.5 at the time of writing this.
Please note however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
