### ISSUE TITLE
Provide "Search All" from Dashboard Widget

### ISSUE THREAD

**Issue by sushinger** [algolia/algoliasearch-wordpress#790]
**Feature Request**

At the moment it's possible to search all post-types (published and drafts) for a certain string from my [Algolia Dashboard](https://www.algolia.com/apps/), but not from my dashboard.

From WP-frontpage only published articles are being displayed.

I'd like to be able to search for **any string** within **any post-types** of **any status** from a Dashboard-Widget. This would be very convenient :-)

Do you provide a feature-request voting-option (like [uservoice](uservoice.com) etc.)?

Thank you,
Sascha

**Comment by rayrutjes** [comment]
Hello @sushinger ,

Thanks for posting this feature request.

As of today, we do not provide a global admin search, however I do remember this topic has been discussed before on our forum.

I'd love to hear a bit more about your current struggles with the default search, and maybe I'll be able to direct you towards a solution.

**Comment by sushinger** [comment]
Hello @rayrutjes 

thank you for your reply, sorry for delay.

I have moved a few posts that were categorized as tutorials, to a new custom post type. Some topics being described, tutored or discussed are now kinda "spread" over 3 differnt post types, regular, pages and tutorials.

Sometimes I tutorials and other instructions are changing, and in order to keep all of this topics on different post types up to date, I need to see all of this topics occurances in order to compare, which one I need to adjust. It's even more complicated as it sounds.

At the moment I'm using my Algolia dashboard, but I cannot add other members of the site to my Algolia account, that's why it would be nice to have a global search in WP-dashboard. Because on my Algolia account is connected with 2 other of my sites, that I don't want my editor to access as well.

**Comment by rayrutjes** [comment]
Hi again @sushinger ,

Thanks for sharing the use case.
Having a global admin search powered by Algolia makes a lot of sense.
I don't think we'll ever release this kind of feature as part of this plugin though.

You would have to go ahead and create a custom extension.

Let us know if you end up going down that road.

Regarding your Algolia account, you should be able to add more team members to your project in order to share access.

I'm closing this issues as there is nothing actionable for this repository, however feel free to continue the discussion.
