### ISSUE TITLE
Parse error: syntax error, unexpected '[' in /home/inurbana/public_html/inurbanas/wp-content/plugins/algoliasearch-wordpress-develop/core/Registry.php on line 31

### ISSUE THREAD

**Issue by danielevz** [algolia/algoliasearch-wordpress#82]
Trying to install and i get this error:

Fatal Error:

Parse error: syntax error, unexpected '[' in /home/inurbana/public_html/inurbanas/wp-content/plugins/algoliasearch-wordpress-develop/core/Registry.php on line 31

**Comment by maxiloc** [comment]
What version of php are you using ?

**Comment by rayrutjes** [comment]
We will try to keep compatibility with PHP 5.3 in the upcoming release.

**Comment by rayrutjes** [comment]
Hi @danielevz , not sure if this issue is still valid in the latest version of the plugin, 0.2.5 at the time of writing this.
Please note however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
