### ISSUE TITLE
WP Admin Tabs

### ISSUE THREAD

**Issue by kylehotchkiss** [algolia/algoliasearch-wordpress#83]
Is it possible to rename some of the tabs from "configration" to "config" to reduce the tab overlap? I had the admin at fullscreen on a 15in laptop and they still broke down into two lines.

<img width="1061" alt="screen shot 2016-03-18 at 4 30 44 pm" src="https://cloud.githubusercontent.com/assets/108172/13891338/ea79ea42-ed26-11e5-97c8-2cde2028a24c.png">

(I'd be happy to make this change in a pr if its okay)

**Comment by kylehotchkiss** [comment]
Screenshot with change made in my dev console:

<img width="956" alt="screen shot 2016-03-18 at 4 33 34 pm" src="https://cloud.githubusercontent.com/assets/108172/13891393/3164f7ee-ed27-11e5-979a-ad36787d7def.png">

**Comment by rayrutjes** [comment]
Hi @kylehotchkiss,

We have released a brand new version of the plugin, 0.2.5 at the time of writing this.

In the new version we gave a lot of power back to developers regarding the configuration of the indices settings and other search experiences implementation. This results in a much cleaner UI which I was hoping you could explore sometime.

Please note however that this new plugin is not compatible with the previous version.
Be sure to go over the [documentation](https://community.algolia.com/wordpress/installation.html) to get a better sense of the new feature set and to understand how to achieve your objectives.

As this issue was related to 0.0.1 I'm closing it for now.

That being said I'd gladly hear from you again on a new issue.

Thank you so much for the feedback you've provided so far!
