### ISSUE TITLE
Excerpt in Instant Search?

### ISSUE THREAD

**Issue by rentageekmom** [algolia/algoliasearch-wordpress#84]
We've got this running in a dev environment, and instant search is returning the full post content, untruncated. The full post content is indexed, no excerpts, so it needs to be truncated/trimmed before output. 

I've read through a few issues here and it looks like my_excerpt() was intended to truncate these, but I don't see where it's working.

**Comment by maxiloc** [comment]
I actually would recommend to use post_content. We try to truncate it and split it into different field to have a better relevance => https://github.com/algolia/algoliasearch-wordpress/blob/develop/core/WordpressFetcher.php#L118-L191

To index post_excerpt you need to add it to the list of attributes to index.

**Comment by rentageekmom** [comment]
The truncation isn't working though. I'm getting full post content at
nctvclone.flywheelsites.com

**Comment by maxiloc** [comment]
yes the algorithm is a bit naive for now, it just look for h1, h2, ..., p in the first div of post_content.
If you have something deeper it will not work.
This is indeed something that we could improve.

**Comment by rentageekmom** [comment]
There's nothing complex going on here. Simple paragraph tags in these excerpts, so this SHOULD be limiting. 

The template is dumping out {{{ _highlightResult.post_content.value }}}. I've tried a few ways to excerpt it manually and not getting anywhere -- any direction here? I've also tried using snippets in algoliasearch.php

**Comment by maxiloc** [comment]
If you want to use attributesToSnippet, you'll need to:

- add the param here: https://github.com/algolia/algoliasearch-wordpress/blob/develop/core/AlgoliaHelper.php#L131
- Replace _highlightResult by _snippetResult here https://github.com/algolia/algoliasearch-wordpress/blob/develop/templates/default/templates.php#L118

**Comment by rayrutjes** [comment]
Hi @rentageekmom , not sure if this issue is still valid in the latest version of the plugin, 0.2.5 at the time of writing this.
Please note however that this new version is not compatible with 0.0.1 and that the features have changed.

In the new version of the plugin we split up the `post_content` based on the DOM.
Under the hood we use this library to turn DOM into Algolia records: https://github.com/algolia/php-dom-parser

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
