### ISSUE TITLE
Extra fields checkboxes are unchecked after refresh

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-wordpress#87]
You can add extra fields to be indexed, save your settings, and all works well. However, the boxes to add the extra fields becomes unchecked after a refresh, so when you save them again, you lose all your settings.

**Comment by rayrutjes** [comment]
This issue should be fixed in the new version, 0.2.5 at the time of writing this.
Please note however that this new version is not compatible with 0.0.1 and that the features have changed.

In the latest version of the plugin, we gave back some power to the developers. To make most of the adjustments you must use WordPress filters. 

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
