### ISSUE TITLE
I get a notice for every imported post

### ISSUE THREAD

**Issue by fschroiff** [algolia/algoliasearch-wordpress#88]
`Notice: Undefined property: stdClass::$Array in /wp-content/plugins/algoliasearch-wordpress-develop/core/WordpressFetcher.php on line 198`

Import seems to have worked though.

**Comment by maxiloc** [comment]
which php version are you using ?

**Comment by fschroiff** [comment]
7.0.0

**Comment by maxiloc** [comment]
Ok that might explain,

can you try to replace ```$data->$attribute['name']``` by ```$data->{$attribute['name']}```

**Comment by fschroiff** [comment]
That works without `notices`!

**Comment by maxiloc** [comment]
Ok cool, i am letting this open as we need to fix it

**Comment by rayrutjes** [comment]
Hi @fschroiff, not sure if this issue is still valid in the latest version of the plugin, 0.2.5 at the time of writing this.
Please note however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
