### ISSUE TITLE
Saving algoliasearch "templates" in plugin folder is a bad idea. 

### ISSUE THREAD

**Issue by fschroiff** [algolia/algoliasearch-wordpress#90]
Plugins can be auto-updated (hopefully the algoliasearch plugin too in the future), so storing any user-generated stuff in there is not a good plan. 

Two better options:
1. let me store an "algolia-template" folder in my active theme
2. algolia-templates are plugins

**Comment by rayrutjes** [comment]
@fschroiff In the next upcoming release, we have done a lot of work regarding wordpress coding standards.
You will be able to properly add behaviour or alter templates without having to worry about BC when upgrading.

**Comment by rayrutjes** [comment]
Hi again @fschroiff, 

Let me add some context before going straight to the answer for other users that might land on this issue.

We released a new version of the plugin, 0.2.5 at the time of writing this.

In the new version, we gave a lot of power back to the developers regarding the implementation of custom search experiences.
- Static assets are now registered and can be selected as dependencies when enqueuing scripts
- We no longer provide an out of the box instantsearch.js integration but instead make everything available so that you can easily implement it on your own
- We provide a plug & play alternative to the native wordpress search that takes place in the backend
- We provide a plug & play autocomplete.js dropdown search experience that is configurable in the admin UI

We plan to release the plugin to the WordPress plugin directory in the near future.
As we no longer rely on the filesystem, you should have no problem upgrading the plugin.

I'm closing this issue as it was related to the version 0.0.1 of the plugin.

Please open a new issue if you have additional inputs regarding plugin updates!
