### ISSUE TITLE
Automate re-index/real-time updating

### ISSUE THREAD

**Issue by ddibiase** [algolia/algoliasearch-wordpress#96]
Hi there,

A lot of the content in our WP platform is quite timely. I'm wondering if the plugin propagates updates on publish of a post type whenever it's made? If not we're very interested in finding a way to automate the process in batch every x hours or so.

Any suggestions regarding best practice to net the result we're looking for?

Thanks,

David

**Comment by rayrutjes** [comment]
Hi @ddibiase, We are actually working on a new release which will be more focused on data synchronization with Algolia.

In the meantime, could you maybe tell me more about your use case, your issue with the current plugin, and the expected behaviour that would fix your problem?

Cheers

**Comment by ddibiase** [comment]
@rayrutjes we're using Algolia for a speaker management platform @ nsb.com. All speaker profiles are managed in a custom type. We have a custom filter setup that modifies the data before being sent to Algolia (using the built in plugin hook). On save of every profile the content currently doesn't get automatically updated to Algolia, so we need a process that propagates the values automatically hour or based on a schedule.

Our platform sees many changes throughout the day, so manually clicking the re-index button via the plug-in is very time-consuming. Automating the process will simplify the implementation and make Algolia easier for us to use. So while there's nothing "wrong" with the plug-in we're simply hoping for some advice to help setup the cron process. Is there a hook we can depend on to trigger the re-index? If so we can simply plug that into our cron process. Alternatively if there's a hook we can call to push an update on a single record we can trigger it on a post save.

Any suggestions/support would be most appreciated.

**Comment by rayrutjes** [comment]
HI @ddibiase, thank you for this very detailed explanation. We have re-worked the plugin to provide our users with better control over the indexing flow. We will be able to share it publicly in about a month. /cc @svenhutchinson.
The new version provides a built in task queue mechanism which in turn is coupled to the native WP_Cron mechanism. 
It will also provide a way to override the native WP search and offer a nice `autocomplete.js` search out of the box.

We have have moved the instantsearch and the WooCommerce from the scope for now, those being very dependent on the kind of search experience you want to build, and impacting every theme and template differently.
We definitely want to add support for these features in the future but we first want to make sure our core synchronization workflow works great for every one. We will need to make sure that everything we add to this plugin will really benefit to everyone. We are also considering creating specific plugins for WooCommerce or InstantSearch on top of this one to isolate these topics while still leveraging the same core indexing mechanism, what do you think?

In any case, you should be able to build any kind of Algolia related search experience with the new version by extending properly the plugin.

We are currently working on the user and developer documentations to make it obvious how to achieve custom ranking, custom attributes pushing, cron tweaking etc.

You are speaking of custom content types, are these `Post Types`? We will natively support the indexing of every post types, taxonomies and users. So if your custom type is a post type, you will be able to index it and customize the attributes to push with standard WP filters.

By the way we started building a list of private Beta users for the new version of the plugin. I would be very glad to share with you our work so that you can experiment with it. 

We really care about your feedback, so please do not hesitate to drop us your thoughts on it.

**Comment by ddibiase** [comment]
@rayrutjes thanks for the response. Is there any way we can implement a solution currently? We'd really like to resolve this and continue to utilize Algolia's WP integration. Any advice on practically implementing this now? We're obviously very keen on the release that's a month away but in the interim we need something to hold down the fort.

Thanks!

**Comment by rayrutjes** [comment]
Ok let me try to help you on your use case.

What kind of custom fields would like to push automatically? Native field? Meta field? other?
Is your custom type a post type?

**Comment by ddibiase** [comment]
Yup it's a custom post type and we have a number of meta fields that need to be propagated. We have a pretty intensive filter hook (built into the build) that's adjusting the data before it gets to Algolia though.

**Comment by ddibiase** [comment]
@rayrutjes haven't heard back yet. Help? :-(

**Comment by rayrutjes** [comment]
@ddibiase any chance you could send me a support request on support+wordpress@algolia.com?

**Comment by rayrutjes** [comment]
Hi @ddibiase, new release is out, 0.2.5 at the time of writing this.
Please note however that this new version is not compatible with 0.0.1 and that the features have changed.

The [documentation](https://community.algolia.com/wordpress/installation.html) will give you an overview of what can be achieved with the new plugin.

We also have a list of [Frequently asked questions](https://community.algolia.com/wordpress/frequently-asked-questions.html)

I am closing this issue as it relates to version 0.0.1, but if you think it still applies to the new version, please create a new issue.

Also, if you have a question that the documentation doesn't cover, or if you want to report a problem or simply suggest a feature, please re-open an issue.
