### ISSUE TITLE
Overriding settings with hook

### ISSUE THREAD

**Issue by ddibiase** [algolia/algoliasearch-wordpress#98]
I'm attempting to add in attributes that should be indexed via the hook. I realize I could simply create a new template however I only have 3-4 fields to incorporate. This is what I'm doing:

    // Add specialized filter option
    add_filter('prepare_algolia_set_settings', function($index_name, $settings)
    {
        if ($index_name == 'nsb_speakers')
        {
            $settings['attributesToIndex'][] = array(
                'name' => 'bio',
                'group' => 'Record attribute',
                'ordered' => 'ordered',
                'searchable' => true,
                'retrievable' => true
            );
            $settings['attributesToIndex'][] = array(
                'name' => 'trueline',
                'group' => 'Record attribute',
                'ordered' => 'ordered',
                'searchable' => true,
                'retrievable' => true
            );
            $settings['attributesToIndex'][] = array(
                'name' => 'awards',
                'group' => 'Record attribute',
                'ordered' => 'ordered',
                'searchable' => true,
                'retrievable' => true
            );
            $settings['attributesToIndex'][] = array(
                'name' => 'presentations',
                'group' => 'Record attribute',
                'ordered' => 'ordered',
                'searchable' => true,
                'retrievable' => true
            );
        }
        return $settings;
    }, 10, 3);

When I attempt reindexing the progress bar hangs. There isn't much documentation to describe how the object is structured or how to manipulate the values easily. Would someone be so kind as to validate the above snippet or describe the $settings variable structure?

**Comment by ddibiase** [comment]
Does anyone have any ideas on this? Could REALLY use the insight.

**Comment by rayrutjes** [comment]
Hi @ddibiase, you probably know by now that we released a very new version of the plugin, 0.2.6 at the time of writing this.

In the new version, overriding settings is fairly easy. Please take a look at the documentation and let me know if you are able to achieve what you need: https://community.algolia.com/wordpress/indexing-settings.html

I'm closing this because it was related to version 0.0.1, I'd be glad seing you open a new issue if you still think there are issues related to overriding settings or anything else.

We really appreciate all the feedback you have given us so far!
